name: Deploy TechStore API to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 266949372933
  ECR_REPOSITORY: techstore-api
  ECS_CLUSTER: techstore-cluster-01
  ECS_SERVICE: techstore-service-v2

defaults:
  run:
    shell: powershell

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ejecutar pruebas con Maven
        run: .\mvnw.cmd clean test

      - name: Empaquetar proyecto
        run: .\mvnw.cmd clean package -DskipTests

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verificar identidad AWS
        run: aws sts get-caller-identity

      - name: Login en Amazon ECR
        run: |
          aws ecr get-login-password --region $env:AWS_REGION | docker login --username AWS --password-stdin "$env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com"

      - name: Construir imagen Docker
        run: docker build -t "$env:ECR_REPOSITORY:latest" .

      - name: Etiquetar imagen Docker
        run: docker tag "$env:ECR_REPOSITORY:latest" "$env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com/$env:ECR_REPOSITORY:latest"

      - name: Subir imagen a Amazon ECR
        run: docker push "$env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com/$env:ECR_REPOSITORY:latest"

      - name: Actualizar servicio ECS Fargate
        run: |
          aws ecs update-service --cluster $env:ECS_CLUSTER --service $env:ECS_SERVICE --force-new-deployment
          aws ecs wait services-stable --cluster $env:ECS_CLUSTER --services $env:ECS_SERVICE
